// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfjwwsvipefnbrsdmbky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmand3c3ZpcGVmbmJyc2RtYmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODUyMDgsImV4cCI6MjA2NTI2MTIwOH0._4mY3wHnuIBUzuZaKW4-nYPVCbk7kmqH6ymIzr157k4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);